services:
    david63.resetlogin.admin.controller:
        class: david63\resetlogin\controller\admin_controller
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@request'
            - '@template'
            - '@user'
            - '@log'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@language'
            - '@david63.resetlogin.core.functions'
            - '%tables%'

    david63.resetlogin.core.functions:
        class: david63\resetlogin\core\functions
        arguments:
            - '@ext.manager'

    _defaults:
        public: true
